### ISSUE TITLE
Build syntax is out of date snake case -> camel case (i.e. expects secret_env & kms_key_name instead of secretEnv, kmsKeyName etc.)

### ISSUE THREAD

**Issue by vadakattu** [googleapis/python-cloudbuild#10]
`google-cloud-build` version: `0.1.0`

#### Steps to reproduce

  1. The 'schema' defined in the build protobuf is out of date with the cloudbuild api, as the naming convention appears to have shifted from snake case to camel case

#### Code example

```python
from google.cloud.devtools import cloudbuild_v1

client = cloudbuild_v1.CloudBuildClient()
PROJECT='test'
client.create_build(PROJECT,
{
    "steps": [
        {
            "name": "gcr.io/cloud-build/docker",
            "args": [
                "--help"
            ],
            'secretEnv': [
                "PASSWORD"
            ]
        }
    ],
    "secrets": [
        {
            "kmsKeyName": f"projects/{PROJECT}/locations/global/keyRings/dummy/cryptoKeys/cloud-build",
            "secretEnv": {
                "PASSWORD": "CiQA3WM5zlZnmdJcqs+LMT9cBfK9YzdNxlFOXnpI7j/zkJJwQLwSSQA2zTEX3jOkBpMw5032bDdtxqjCe92+H1oIB6JzLRltyqmedfxOg/gtbagSp7yKMshTl5jAWRAeBegVOQUL+7mxvEmGYYk/xWg="
            }
        }
    ]
})
```

#### Stack trace
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-43-470746238c7f>", line 18, in <module>
    "PASSWORD": "CiQA3WM5zlZnmdJcqs+LMT9cBfK9YzdNxlFOXnpI7j/zkJJwQLwSSQA2zTEX3jOkBpMw5032bDdtxqjCe92+H1oIB6JzLRltyqmedfxOg/gtbagSp7yKMshTl5jAWRAeBegVOQUL+7mxvEmGYYk/xWg="
  File "/usr/local/lib/python3.7/site-packages/google/cloud/devtools/cloudbuild_v1/gapic/cloud_build_client.py", line 263, in create_build
    request = cloudbuild_pb2.CreateBuildRequest(project_id=project_id, build=build)
ValueError: Protocol message BuildStep has no "secretEnv" field.
```

And similarly `ValueError: Protocol message Secret has no "kmsKeyName" field.`

It seems at some point there was a change from snake case to camel case for the core API and all externally facing documentation.

While YAMLs and jsons reference secretEnv, kmsKeyName etc, the python client uses secret_env & kms_key_name etc. but this is not documented anywhere (had to read `cloudbuild_pb2.CreateBuildRequest`)

Either the documentation ought to be updated, or the syntax unified.

**Comment by busunkim96** [comment]
I believe this is working as intended. 

The types documentation for this [library](https://googleapis.dev/python/cloudbuild/latest/gapic/v1/types.html#google.cloud.devtools.cloudbuild_v1.types.Build) consistently uses snake case for field names. 

The short explanation is that the API proto is defined using snakeCase (see [REST API docs](https://cloud.google.com/cloud-build/docs/api/reference/rest/Shared.Types/Build), but the Python representation (pb2 files) use snake case to follow language convention.

Let us know if you have additional questions!
