### ISSUE TITLE
Very high frequency of Bad Gateway responses on create_build

### ISSUE THREAD

**Issue by G-Goldstein** [googleapis/python-cloudbuild#16]
I've created a Python script to run as a Cloud Function, which uses this library to initiate an adhoc cloud build. Its purpose is to retrieve an image from the Google Container Registry and push it to a private registry. And it works sometimes, but it usually fails to create the build at all, even with an identical run. I've tried wrapping the process in retries and increasing timeouts, but even with these in place the rate of failure for the whole process is about 50%, and I've ended up with Cloud Functions that run for 5 minutes while they repeatedly retry creation of the build before failing. I've attached a sanitised version of the code and the console output from one of these failed runs, where I invoke the `release` function directly.

[requirements.txt](https://github.com/googleapis/python-cloudbuild/files/4731050/requirements.txt)
[console.txt](https://github.com/googleapis/python-cloudbuild/files/4731051/console.txt)
[main.py](https://github.com/googleapis/python-cloudbuild/files/4731055/main.py.txt)

I understand that no services are infallible, but GCP's status dashboard reports no issues and I'm getting an extremely high rate of failure. At the moment I'm left with the advice to my team of "If it hasn't worked after five minutes, just retry it and cross your fingers", which isn't great. Does the issue lie in the Cloud Builds API itself, or am I doing something wrong here?

**Comment by busunkim96** [comment]
@G-Goldstein Do you have any information on when this behavior started? (Or has it always been this way)?

**Comment by busunkim96** [comment]
If you have a support contract with Google, please make sure to reach out via that channel as well. https://cloud.google.com/support/

Are you also able to provide a more detailed error message?

**Comment by G-Goldstein** [comment]
I posted this issue on the first day of creating the script I was using, so I was seeing it every time. However, I've just given it another thorough test and it seems to be working reliably now without any changes. I suspect this might have been due to an incident within GCP itself. Apologies!

**Comment by busunkim96** [comment]
Good to hear it's been resolved. :) Thanks for the update!
