### ISSUE TITLE
create_build fails with "Protocol message BuildStep has no "secretEnv" field" error

### ISSUE THREAD

**Issue by SaschaHeyer** [googleapis/python-cloudbuild#169]
Hello Google Team,

getting the following error when following this documentation https://cloud.google.com/build/docs/access-github-from-build
`Protocol message BuildStep has no "secretEnv" field.`

#### Environment details

Please see notebook for reproduction 
https://colab.research.google.com/drive/1MqJrGDk2pae4h2gkCL-SampZ0U4gjjkq?usp=sharing

#### Steps to reproduce

Please see notebook for reproduction 
https://colab.research.google.com/drive/1MqJrGDk2pae4h2gkCL-SampZ0U4gjjkq?usp=sharing

#### Code example

Please see notebook for reproduction 
https://colab.research.google.com/drive/1MqJrGDk2pae4h2gkCL-SampZ0U4gjjkq?usp=sharing

#### Stack trace
Please see notebook for reproduction 
https://colab.research.google.com/drive/1MqJrGDk2pae4h2gkCL-SampZ0U4gjjkq?usp=sharing

Best regards
Sascha

**Comment by dinagraves** [comment]
Hi Sascha!  Thank you for surfacing this!  In the Python client library, this field is actually called `secret_env`.  You can see the documentation on this field and more in the client library [reference documentation](https://googleapis.dev/python/cloudbuild/latest/cloudbuild_v1/types.html#google.cloud.devtools.cloudbuild_v1.types.BuildStep.secret_env).
