### ISSUE TITLE
Trigger existing cloud build with the parameters 

### ISSUE THREAD

**Issue by vishnu123sai** [googleapis/python-cloudbuild#198]
Hi Team,

Do we have support to trigger existing cloud build with the parameters.

**Comment by dinagraves** [comment]
Hi Vishnu,

Can you describe your issue with more detail?  Please feel free to re-open with more information.

Thank you,
Dina

**Comment by rasalamadhu1** [comment]
Trigger existing cloud build with the parameters  instead creating new build i have seen an example where you have created a build and triggered it but i want to trigger a existing cloud build, can you help me how can i achieve this?

**Comment by muzaffersenkal** [comment]
> Trigger existing cloud build with the parameters instead creating new build i have seen an example where you have created a build and triggered it but i want to trigger a existing cloud build, can you help me how can i achieve this?

Hi @vishnu123sai;

I guess you want to run your trigger via google build API. You can run your existing trigger like that ;

```

client = cloudbuild.CloudBuildClient(credentials=credentials)

build_item = {
    "project_id": "modelifyproject",
    "trigger_id": "f5bf613d-8352-40b0-9e79-b5fa508a05ec",
    "source": {
        "substitutions": {
            "_APP_ID": "SCjRGfGtTJwcrI9eSmu0",
            "_APP_ID_L": "scjrgfgttjwcri9esmu0",
            "_USER_ID": "D2AQSd95xUZMmORxaM3yEHPqvJj1",
            "_USER_ID_L": "d2aqsd95xuzmmorxam3yehpqvjj1",
            "_SERVICE_NAME": "python-test-scjrgfgt",
            "_VERSION_ID": "1"
        }
    }
}

s = client.run_build_trigger(build_item)
```

**Comment by muzaffersenkal** [comment]
> Trigger existing cloud build with the parameters instead creating new build i have seen an example where you have created a build and triggered it but i want to trigger a existing cloud build, can you help me how can i achieve this?

Hi @vishnu123sai;

I guess you want to run your trigger via google build API. You can run your existing trigger like that ;

```
from google.oauth2 import service_account
from google.cloud.devtools import cloudbuild

credentials = service_account.Credentials.from_service_account_file("service_account.json")

client = cloudbuild.CloudBuildClient(credentials=credentials)

build_item = {
    "project_id": "YOUR PROJECT ID",
    "trigger_id": "YOUR TRIGGER ID", 
    "source": {
        "substitutions": {
            "_FOO": "BAR",
        }
    }
}

client.run_build_trigger(build_item)
```
