### ISSUE TITLE
Timeout settings for v2.0.0

### ISSUE THREAD

**Issue by sfujiwara** [googleapis/python-cloudbuild#30]
**Is your feature request related to a problem? Please describe.**

When using google-cloud-build v2.0.0, we specifies `timeout` as below.
It's a little bit confusing to use `google.protobuf.duration_pb2` and `timedelta`.

```python
from datetime import timedelta
from google.cloud.devtools import cloudbuild_v1
from google.protobuf.duration_pb2 import Duration

build = {
    "steps": [
        {
            "name": "ubuntu",
            "args": ["sleep", "100"],
            # We could not pass int or float here.
            "timeout": duration.FromTimedelta(timedelta(seconds=10))
        }
    ],
    # We could not pass int or float here.
    "timeout": duration,
}
client = cloudbuild_v1.CloudBuildClient()

response = client.create_build(
    project_id="xxx",
    build=cloudbuild_v1.Build(build),
)
```

 **Describe the solution you'd like**

I guess it's better that we could specifies the timeout by numeric or a simple class like `cloudbuild_v1.Build` as below:

```python
{
    "name": "ubuntu",
    "args": ["sleep", "100"],
    # Specify by numeric.
    "timeout": 10
}
```

```python
{
    "name": "ubuntu",
    "args": ["sleep", "100"],
    # I'm happy if there is a simple class like `cloudbuild_v1.Build`.
    "timeout": cloudbuild_v1.Timeout(10)
}
```

 **Additional context**

It was tough to know how to set the timeout because the official document seems to be written only for version 1.x.x.
I'm very happy if it would be updated!

https://googleapis.dev/python/cloudbuild/latest/gapic/v1/api.html?highlight=create_build#google.cloud.devtools.cloudbuild_v1.CloudBuildClient.create_build

**Comment by donmccasland** [comment]
I'm not sure it is possible to change this back to the v1 method

**Comment by engelke** [comment]
This is documented as a breaking change for v2, and has been in use for a considerable time.
