### ISSUE TITLE
Allow cloud-build-local to run internally

### ISSUE THREAD

**Issue by takehaya** [googleapis/python-cloudbuild#31]
**Is your feature request related to a problem? Please describe.**
I want to run my application locally using CloudBuild.
But there is no solution from the library to connect to the emulator. Other appliances (e.g. pubsub, gcs, firestore...) etc.), but it's inconvenient to not be able to use them in cloudbuild

 **Describe the solution you'd like**
Run cloud-build-local internally to emulate it

 **Additional context**
If no one else is going to implement it, I would like to implement it myself. Would you support me?

**Comment by donmccasland** [comment]
Can you describe in detail how you would like this to work?

**Comment by takehaya** [comment]
hi. @donmccasland Sorry for the delay :bow:

> Can you describe in detail how you would like this to work?
yep. I want to run a cloud build running locally in python.
https://cloud.google.com/cloud-build/docs/build-debug-locally
Examples of use case include CI/CD, local development.


for example
```
# env
export CLOUD_BUILD_IS_LOCAL="1"
python cloudbuild.py # when internal  run cloud-build-local if env is 1 
```
We want a mechanism like this
