### ISSUE TITLE
log_url field in cloudbuild_v1.Build() should be filled when object created.

### ISSUE THREAD

**Issue by y1chi** [googleapis/python-cloudbuild#41]
**Is your feature request related to a problem? Please describe.**
There seems no convenient way to get Google Cloud Build log url until operation finishes successfully
 **Describe the solution you'd like**
I'm using the client as follows:
```
build = cloudbuild_v1.Build()
build.steps = [...]
operation = client.create_build(project_id=project, build=build)
result = operation.result()
```
The build object should contain the build history log url but it seems always None. The result does contain the log url if it finishes successfully, but seems unable to get the url if exception happens or build failed. It would be much better in terms of visibility if we can get the log url even before the build finishes.
 **Describe alternatives you've considered**
I've been using client.list_builds() with filter to get the log url which seems not ideal.

**Comment by dinagraves** [comment]
Try this!

The method `create_build` returns an operation, which contains the metadata of the build.  You can pull this info out immediately, before the build even starts (ie, when it's queued).

```
from google.cloud.devtools import cloudbuild_v1

client = cloudbuild_v1.services.cloud_build.CloudBuildClient()
build = cloudbuild_v1.Build()
build.steps = [{"name": "ubuntu", 
                "entrypoint": "bash",
                "args": ["-c", "echo hello world"]}]
operation = client.create_build(project_id=PROJECT_ID, build=build)
print(operation.metadata)

result = operation.result()
```

For the log_url, the exact field you want is `operation.metadata.build.log_url`
